apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
    - 172.31.217.43:6789
    - 172.31.217.45:6789
    - 172.31.217.44:6789
    - 172.31.217.53:6789
    path: /hello
    user: admin
    secretRef:
      name: default-secret-admin-ceph
