version: '3.2'
services:

  promethues:
    image: prom/prometheus:latest
    container_name: promethues
    volumes:
      - /etc/localtime:/etc/localtime
      - ./promethues/conf.d/:/etc/prometheus/
      - ./promethues/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: always
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /etc/localtime:/etc/localtime
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
    ports:
      - 9100:9100
    restart: always
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - /etc/localtime:/etc/localtime
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /etc/localtime:/etc/localtime
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "104"
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/devops/grafana/data:/var/lib/grafana
    restart: always
