apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-ops
  labels:
    app: grafana
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: grafana
