global:
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
 group_by: [cluster]
 # If an alert isn't caught by a route, send it slack.
 receiver: slack_general
 routes:
  # Send severity=slack alerts to slack.
  - match:
      severity: slack
    receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#monitor'
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    send_resolved: true
