apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-demo-nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dep-web
    spec:
      containers:
      - name: web
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-demo-nginx-service
spec:
  selector:
    app: dep-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
