apiVersion: v1
kind: Pod
metadata:
  name: lnmp
  labels:
    name: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
    - name: php
      image: php:7-fpm
      imagePullPolicy: IfNotPresent
