kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
  namespace: kube-system
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
