kind: Pod
apiVersion: v1
metadata:
  name: test-pod
  namespace: kube-system
spec:
  containers:
  - name: test-pod
    image: nginx
    volumeMounts:
      - name: pvc
        mountPath: "/mnt"
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: claim1
