apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-nginx-podaffinity
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: affinity
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: nginxweb
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: hello
                operator: In
                values:
                - world
            topologyKey: kubernetes.io/hostname
