apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
data:
  key: QVFDN28wZGRSaDVkRkJBQTVFMkJoSlVmWFJKNnNURzA4YU5UTUE9PQ==
type: "kubernetes.io/rbd"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 172.31.217.45:6789,172.31.217.43:6789,172.31.217.44:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: default
  pool: rbd
  userId: admin
  userSecretName: ceph-secret-admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-pvc-test
spec:
  accessModes:     
  - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 500Mi
